// Generated by gencpp from file project_cam/CustomServiceResponse.msg
// DO NOT EDIT!


#ifndef PROJECT_CAM_MESSAGE_CUSTOMSERVICERESPONSE_H
#define PROJECT_CAM_MESSAGE_CUSTOMSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_cam
{
template <class ContainerAllocator>
struct CustomServiceResponse_
{
  typedef CustomServiceResponse_<ContainerAllocator> Type;

  CustomServiceResponse_()
    : success(false)  {
    }
  CustomServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::project_cam::CustomServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_cam::CustomServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServiceResponse_

typedef ::project_cam::CustomServiceResponse_<std::allocator<void> > CustomServiceResponse;

typedef boost::shared_ptr< ::project_cam::CustomServiceResponse > CustomServiceResponsePtr;
typedef boost::shared_ptr< ::project_cam::CustomServiceResponse const> CustomServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_cam::CustomServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_cam::CustomServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::project_cam::CustomServiceResponse_<ContainerAllocator1> & lhs, const ::project_cam::CustomServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::project_cam::CustomServiceResponse_<ContainerAllocator1> & lhs, const ::project_cam::CustomServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace project_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::project_cam::CustomServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_cam::CustomServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_cam::CustomServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_cam::CustomServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_cam::CustomServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_cam::CustomServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_cam::CustomServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::project_cam::CustomServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::project_cam::CustomServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_cam/CustomServiceResponse";
  }

  static const char* value(const ::project_cam::CustomServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_cam::CustomServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::project_cam::CustomServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_cam::CustomServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_cam::CustomServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_cam::CustomServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_CAM_MESSAGE_CUSTOMSERVICERESPONSE_H
