// Generated by gencpp from file project_cam/CustomService.msg
// DO NOT EDIT!


#ifndef PROJECT_CAM_MESSAGE_CUSTOMSERVICE_H
#define PROJECT_CAM_MESSAGE_CUSTOMSERVICE_H

#include <ros/service_traits.h>


#include <project_cam/CustomServiceRequest.h>
#include <project_cam/CustomServiceResponse.h>


namespace project_cam
{

struct CustomService
{

typedef CustomServiceRequest Request;
typedef CustomServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomService
} // namespace project_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project_cam::CustomService > {
  static const char* value()
  {
    return "3291d4b5bdf7cffb16ecf585381bb69a";
  }

  static const char* value(const ::project_cam::CustomService&) { return value(); }
};

template<>
struct DataType< ::project_cam::CustomService > {
  static const char* value()
  {
    return "project_cam/CustomService";
  }

  static const char* value(const ::project_cam::CustomService&) { return value(); }
};


// service_traits::MD5Sum< ::project_cam::CustomServiceRequest> should match
// service_traits::MD5Sum< ::project_cam::CustomService >
template<>
struct MD5Sum< ::project_cam::CustomServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project_cam::CustomService >::value();
  }
  static const char* value(const ::project_cam::CustomServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_cam::CustomServiceRequest> should match
// service_traits::DataType< ::project_cam::CustomService >
template<>
struct DataType< ::project_cam::CustomServiceRequest>
{
  static const char* value()
  {
    return DataType< ::project_cam::CustomService >::value();
  }
  static const char* value(const ::project_cam::CustomServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project_cam::CustomServiceResponse> should match
// service_traits::MD5Sum< ::project_cam::CustomService >
template<>
struct MD5Sum< ::project_cam::CustomServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project_cam::CustomService >::value();
  }
  static const char* value(const ::project_cam::CustomServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_cam::CustomServiceResponse> should match
// service_traits::DataType< ::project_cam::CustomService >
template<>
struct DataType< ::project_cam::CustomServiceResponse>
{
  static const char* value()
  {
    return DataType< ::project_cam::CustomService >::value();
  }
  static const char* value(const ::project_cam::CustomServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_CAM_MESSAGE_CUSTOMSERVICE_H
