// Generated by gencpp from file project_cam/CustomServiceRequest.msg
// DO NOT EDIT!


#ifndef PROJECT_CAM_MESSAGE_CUSTOMSERVICEREQUEST_H
#define PROJECT_CAM_MESSAGE_CUSTOMSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_cam
{
template <class ContainerAllocator>
struct CustomServiceRequest_
{
  typedef CustomServiceRequest_<ContainerAllocator> Type;

  CustomServiceRequest_()
    : input()  {
    }
  CustomServiceRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::project_cam::CustomServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_cam::CustomServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServiceRequest_

typedef ::project_cam::CustomServiceRequest_<std::allocator<void> > CustomServiceRequest;

typedef boost::shared_ptr< ::project_cam::CustomServiceRequest > CustomServiceRequestPtr;
typedef boost::shared_ptr< ::project_cam::CustomServiceRequest const> CustomServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_cam::CustomServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_cam::CustomServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::project_cam::CustomServiceRequest_<ContainerAllocator1> & lhs, const ::project_cam::CustomServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::project_cam::CustomServiceRequest_<ContainerAllocator1> & lhs, const ::project_cam::CustomServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace project_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::project_cam::CustomServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_cam::CustomServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_cam::CustomServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_cam::CustomServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_cam::CustomServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_cam::CustomServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_cam::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39e92f1778057359c64c7b8a7d7b19de";
  }

  static const char* value(const ::project_cam::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39e92f1778057359ULL;
  static const uint64_t static_value2 = 0xc64c7b8a7d7b19deULL;
};

template<class ContainerAllocator>
struct DataType< ::project_cam::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_cam/CustomServiceRequest";
  }

  static const char* value(const ::project_cam::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_cam::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input\n"
;
  }

  static const char* value(const ::project_cam::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_cam::CustomServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_cam::CustomServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_cam::CustomServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_CAM_MESSAGE_CUSTOMSERVICEREQUEST_H
