controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link_cyclnder_joint
      - cylinder_link_first_box_joint
      - first_box_second_box_joint
      - second_box_third_box_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - grabber_link_garbber_right_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: up
  - group: gripper
    pose: open